apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::440878854771:role/cluster-autoscaler-irsa-role



  # annotations:
     #eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/<your-irsa-role-name>

