apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
          - |
            for i in $(seq 1 5000); do
              curl -s -o /dev/null http://my-deploy.default.svc.cluster.local
              sleep 0.1
            done

